# Generated by Django 5.1.1 on 2024-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_championship_options_alter_countries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
