# Generated by Django 5.1.1 on 2024-10-06 18:31

import footballApplication.football.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[footballApplication.football.validators.BadLanguageValidator(['fuck', 'shit'])]),
        ),
    ]
